services:
  chat-service:
    build: ./src
    container_name: watch-party-chat-service-container
    ports:
      - "${PORT}:5000"
    environment:
      PORT: 5000
      MONGO_HOST: mongo      
      MONGO_PORT: 27017    
      MONGO_DB: chatdb     
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: watch-party-chat-service-mongodb-container
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: